### ISSUE TITLE
Override not working

### ISSUE THREAD

**Issue by kcoyner** [meain/vim-printer#4]
`let g:vim_printer_items = {
      'javascript': 'console.log("Log - {$}:", {$})',
      }`

I added the above (note the addition of the word "Log - ") to my .vimrc but it doesn't override the default vim-printer settings for javascript.

Otherwise, nice work.

**Comment by meain** [comment]
@kcoyner I am not able to reproduce the issue on my local.

The only possible reason that I can think of is that your filetype that you are trying it in might be different as in it could be something like `javascript.jsx`. Could you double check?

**Comment by kcoyner** [comment]
I've tried again with no new results.

I added the following to my .vimrc:

> let g:vim_printer_items = {
>       \ 'javascript': 'console.log("Log - {$}:", {$})',
>       \ 'javascript.jsx': 'console.log("Log - {$}:", {$})',
>       \ 'JavaScript': 'console.log("Log - {$}:", {$})',
>       \ 'Javascript': 'console.log("Log - {$}:", {$})',
>       \ 'js': 'console.log("Log - {$}:", {$})',
>       \  }

and

> let g:vim_printer_print_below_keybinding =` '<leader>c'`


So as a further test I changed the keybinding to `<leader>c`, and that doesn't work either. `<leader>p` still works though.  

This is the same .vimrc in which I load the vim-printer plugin using vim-plug.  And like I stated above, it does work with `<leader>p`.

`% vim --version              
NVIM v0.5.0-dev
Build type: RelWithDebInfo
Lua 5.1
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-xZad2y/neovim-0.5.0+ubuntu1+git201912030003-56be9fb-00e710e=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/build/neovim-xZad2y/neovim-0.5.0+ubuntu1+git201912030003-56be9fb-00e710e/build/config -I/build/neovim-xZad2y/neovim-0.5.0+ubuntu1+git201912030003-56be9fb-00e710e/src -I/build/neovim-xZad2y/neovim-0.5.0+ubuntu1+git201912030003-56be9fb-00e710e/.deps/usr/include -I/usr/include -I/build/neovim-xZad2y/neovim-0.5.0+ubuntu1+git201912030003-56be9fb-00e710e/build/src/nvim/auto -I/build/neovim-xZad2y/neovim-0.5.0+ubuntu1+git201912030003-56be9fb-00e710e/build/include
Compiled by buildd@lgw01-amd64-033`

**Comment by meain** [comment]
I tried it in an fresh docker container, still not able to reproduce this. Could you try using this.

```
call plug#begin('~/.vim/plugged')
Plug 'meain/vim-printer'
call plug#end()

let g:vim_printer_items = {
\ 'javascript': 'console.log("Log - {$}:", {$})',
\ 'javascript.jsx': 'console.log("Log - {$}:", {$})',
\ 'JavaScript': 'console.log("Log - {$}:", {$})',
\ 'Javascript': 'console.log("Log - {$}:", {$})',
\ 'js': 'console.log("Log - {$}:", {$})',
\ }

let g:vim_printer_print_below_keybinding = '<leader>c'
```

Also, if possible could you post a link your `vimrc` or `init.vim`

**Comment by kcoyner** [comment]
Here's a link to the init.vim I use:

[init.vim](https://gist.github.com/kcoyner/32199d4a6fe25779918e649c466c1cb2
)

**Comment by meain** [comment]
@kcoyner 

Sorry that it took a little while to respond. From what I understood, your init.vim breaks somewhere before it sources the config for `vim_printer`.

I moved the config to the top and it works(after the `Plug` thingy). It is likely that some other plugin is causing the issue.
